import { MigrationVM, MigrationLog } from '../src/types';

export const INITIAL_VMS: MigrationVM[] = [
  {
    id: 'vm-prod-app-01',
    vmName: 'PRD-APP-WEB-01',
    sourceCluster: 'Cluster-Prod-ESXi',
    sourceDatacenter: 'DC1-Frankfurt',
    sourceHost: 'esxi-04.corp.local',
    sourceDatastore: 'SAN_SSD_VOL_02',
    vcpu: 8,
    ramGb: 32,
    diskGb: 120,
    osType: 'Ubuntu 22.04 LTS',
    ipAddress: '10.20.14.50',
    targetVirtuozzoHost: 'vz-node03.dc1.vhs',
    targetStoragePool: '/vz/storage/nvme-pool1',
    targetVlan: 'VLAN-214-PROD',
    targetVmType: 'kvm',
    wave: 'Wave 1 (Pilot/Web)',
    priority: 'high',
    status: 'converting',
    progress: 58.4,
    speedMbps: 165.2,
    transferredGb: 70.08,
    etaSeconds: 180,
    currentStep: 'qemu-img convert -f vmdk -O qcow2: converting block 71680/122880',
    assignedAdmin: 'DevOps Lead (Alex)',
    scheduledTime: '2026-09-16T08:00:00Z',
    startTime: '2026-09-16T08:05:12Z',
    endTime: null,
    errorMessage: null,
    lastHeartbeat: new Date().toISOString(),
    pythonAgentId: 'vz-worker-worker01'
  },
  {
    id: 'vm-prod-db-01',
    vmName: 'PRD-POSTGRES-MASTER',
    sourceCluster: 'Cluster-Prod-ESXi',
    sourceDatacenter: 'DC1-Frankfurt',
    sourceHost: 'esxi-01.corp.local',
    sourceDatastore: 'SAN_FAST_NVME_01',
    vcpu: 16,
    ramGb: 64,
    diskGb: 450,
    osType: 'Red Hat Enterprise Linux 9.2',
    ipAddress: '10.20.14.12',
    targetVirtuozzoHost: 'vz-node01.dc1.vhs',
    targetStoragePool: '/vz/storage/nvme-pool1',
    targetVlan: 'VLAN-210-DB',
    targetVmType: 'kvm',
    wave: 'Wave 3 (Mission-Critical DBs)',
    priority: 'critical',
    status: 'scheduled',
    progress: 0,
    speedMbps: 0,
    transferredGb: 0,
    etaSeconds: null,
    currentStep: 'Awaiting scheduled maintenance window cutover',
    assignedAdmin: 'Senior DBA (Marcus)',
    scheduledTime: '2026-09-18T22:00:00Z',
    startTime: null,
    endTime: null,
    errorMessage: null,
    lastHeartbeat: null,
    pythonAgentId: null
  },
  {
    id: 'vm-prod-api-02',
    vmName: 'PRD-API-GATEWAY-02',
    sourceCluster: 'Cluster-Prod-ESXi',
    sourceDatacenter: 'DC1-Frankfurt',
    sourceHost: 'esxi-02.corp.local',
    sourceDatastore: 'SAN_SSD_VOL_01',
    vcpu: 4,
    ramGb: 16,
    diskGb: 80,
    osType: 'Debian 12 (Bookworm)',
    ipAddress: '10.20.14.88',
    targetVirtuozzoHost: 'vz-node02.dc1.vhs',
    targetStoragePool: '/vz/storage/nvme-pool1',
    targetVlan: 'VLAN-214-PROD',
    targetVmType: 'kvm',
    wave: 'Wave 1 (Pilot/Web)',
    priority: 'high',
    status: 'completed',
    progress: 100,
    speedMbps: 0,
    transferredGb: 80,
    etaSeconds: 0,
    currentStep: 'Migration verified. Virtuozzo Guest Tools running.',
    assignedAdmin: 'DevOps Lead (Alex)',
    scheduledTime: '2026-09-16T06:00:00Z',
    startTime: '2026-09-16T06:02:10Z',
    endTime: '2026-09-16T06:34:45Z',
    errorMessage: null,
    lastHeartbeat: new Date().toISOString(),
    pythonAgentId: 'vz-worker-worker01'
  },
  {
    id: 'vm-internal-ad-01',
    vmName: 'CORP-WIN-AD01',
    sourceCluster: 'Cluster-Infra-ESXi',
    sourceDatacenter: 'DC1-Frankfurt',
    sourceHost: 'esxi-05.corp.local',
    sourceDatastore: 'SAN_SSD_VOL_03',
    vcpu: 4,
    ramGb: 16,
    diskGb: 150,
    osType: 'Windows Server 2022 Standard',
    ipAddress: '10.20.10.15',
    targetVirtuozzoHost: 'vz-node04.dc1.vhs',
    targetStoragePool: '/vz/storage/sas-pool',
    targetVlan: 'VLAN-100-MGMT',
    targetVmType: 'kvm',
    wave: 'Wave 2 (Internal Infra)',
    priority: 'critical',
    status: 'guest_tools',
    progress: 92,
    speedMbps: 45.0,
    transferredGb: 150,
    etaSeconds: 65,
    currentStep: 'Injecting Virtuozzo VirtIO storage & guest integration drivers',
    assignedAdmin: 'SysAdmin (Sarah)',
    scheduledTime: '2026-09-16T07:15:00Z',
    startTime: '2026-09-16T07:18:04Z',
    endTime: null,
    errorMessage: null,
    lastHeartbeat: new Date().toISOString(),
    pythonAgentId: 'vz-worker-worker02'
  },
  {
    id: 'vm-staging-redis-01',
    vmName: 'STG-REDIS-CACHE',
    sourceCluster: 'Cluster-DevTest',
    sourceDatacenter: 'DC2-Amsterdam',
    sourceHost: 'esxi-dev01.corp.local',
    sourceDatastore: 'LOCAL_DEV_RAID10',
    vcpu: 2,
    ramGb: 8,
    diskGb: 40,
    osType: 'Alpine Linux 3.19',
    ipAddress: '10.30.5.21',
    targetVirtuozzoHost: 'vz-node-dev01.dc2.vhs',
    targetStoragePool: '/vz/storage/dev-pool',
    targetVlan: 'VLAN-300-DEV',
    targetVmType: 'container',
    wave: 'Wave 1 (Pilot/Web)',
    priority: 'low',
    status: 'completed',
    progress: 100,
    speedMbps: 0,
    transferredGb: 40,
    etaSeconds: 0,
    currentStep: 'Virtuozzo container operational and passing health checks',
    assignedAdmin: 'Cloud Eng (Tyler)',
    scheduledTime: '2026-09-15T14:00:00Z',
    startTime: '2026-09-15T14:01:22Z',
    endTime: '2026-09-15T14:18:50Z',
    errorMessage: null,
    lastHeartbeat: new Date().toISOString(),
    pythonAgentId: 'vz-worker-dev'
  },
  {
    id: 'vm-legacy-app-04',
    vmName: 'LEGACY-BILLING-ORACLE',
    sourceCluster: 'Cluster-Legacy',
    sourceDatacenter: 'DC1-Frankfurt',
    sourceHost: 'esxi-legacy02.corp.local',
    sourceDatastore: 'SAN_OLD_FIBRE_01',
    vcpu: 8,
    ramGb: 32,
    diskGb: 320,
    osType: 'Oracle Linux 7.9',
    ipAddress: '10.20.14.99',
    targetVirtuozzoHost: 'vz-node05.dc1.vhs',
    targetStoragePool: '/vz/storage/sas-pool',
    targetVlan: 'VLAN-214-PROD',
    targetVmType: 'kvm',
    wave: 'Wave 2 (Internal Infra)',
    priority: 'high',
    status: 'failed',
    progress: 42,
    speedMbps: 0,
    transferredGb: 134.4,
    etaSeconds: null,
    currentStep: 'Failed at block transfer: network socket timeout to Virtuozzo node',
    assignedAdmin: 'DevOps Lead (Alex)',
    scheduledTime: '2026-09-16T04:00:00Z',
    startTime: '2026-09-16T04:05:00Z',
    endTime: '2026-09-16T04:22:15Z',
    errorMessage: 'SSH pipeline reset by peer during scp of VMDK chunk 4. Target disk has been quarantined for retry.',
    lastHeartbeat: new Date().toISOString(),
    pythonAgentId: 'vz-worker-worker03'
  },
  {
    id: 'vm-monitoring-zabbix',
    vmName: 'INFRA-ZABBIX-MONITOR',
    sourceCluster: 'Cluster-Infra-ESXi',
    sourceDatacenter: 'DC1-Frankfurt',
    sourceHost: 'esxi-06.corp.local',
    sourceDatastore: 'SAN_SSD_VOL_01',
    vcpu: 4,
    ramGb: 16,
    diskGb: 100,
    osType: 'AlmaLinux 9',
    ipAddress: '10.20.10.8',
    targetVirtuozzoHost: 'vz-node02.dc1.vhs',
    targetStoragePool: '/vz/storage/nvme-pool1',
    targetVlan: 'VLAN-100-MGMT',
    targetVmType: 'kvm',
    wave: 'Wave 2 (Internal Infra)',
    priority: 'medium',
    status: 'not_started',
    progress: 0,
    speedMbps: 0,
    transferredGb: 0,
    etaSeconds: null,
    currentStep: 'Pending scheduling approval',
    assignedAdmin: 'SysAdmin (Sarah)',
    scheduledTime: '2026-09-17T10:00:00Z',
    startTime: null,
    endTime: null,
    errorMessage: null,
    lastHeartbeat: null,
    pythonAgentId: null
  }
];

export const INITIAL_LOGS: MigrationLog[] = [
  {
    id: 'log-1',
    vmId: 'vm-prod-app-01',
    vmName: 'PRD-APP-WEB-01',
    timestamp: '2026-09-16T08:05:12Z',
    level: 'info',
    message: 'Pre-flight check passed on vCenter cluster Cluster-Prod-ESXi. VMDK size: 120GB.',
    source: 'python_agent'
  },
  {
    id: 'log-2',
    vmId: 'vm-prod-app-01',
    vmName: 'PRD-APP-WEB-01',
    timestamp: '2026-09-16T08:07:30Z',
    level: 'cmd',
    message: 'ovftool vi://administrator%40vsphere.local:***@vcenter.corp.local/DC1/PRD-APP-WEB-01 ./temp/',
    source: 'python_agent'
  },
  {
    id: 'log-3',
    vmId: 'vm-prod-app-01',
    vmName: 'PRD-APP-WEB-01',
    timestamp: '2026-09-16T08:14:02Z',
    level: 'info',
    message: 'VMDK streamed from VMware ESXi datastore. Initiating qemu-img format conversion to QCOW2 with zstd compression.',
    source: 'python_agent'
  },
  {
    id: 'log-4',
    vmId: 'vm-prod-app-01',
    vmName: 'PRD-APP-WEB-01',
    timestamp: '2026-09-16T08:18:44Z',
    level: 'info',
    message: 'Conversion 58.4% completed. Average pipeline throughput: 165.2 MB/s.',
    source: 'python_agent'
  },
  {
    id: 'log-5',
    vmId: 'vm-legacy-app-04',
    vmName: 'LEGACY-BILLING-ORACLE',
    timestamp: '2026-09-16T04:22:15Z',
    level: 'error',
    message: 'Transfer interrupted: SSH pipeline reset by peer during scp of VMDK chunk 4. Target disk has been quarantined for retry.',
    source: 'python_agent'
  }
];
